### ISSUE TITLE
RubyMine 2021.3 RC: java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/FormLayout

### ISSUE THREAD

**Issue by JunichiIto** [basgren/railways#52]
When I open Routes tab in RubyMine 2021.3 RC, I always get this error:

```
java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/FormLayout
	at net.bitpot.railways.gui.MainPanel.$$$setupUI$$$(Unknown Source)
	at net.bitpot.railways.gui.MainPanel.<init>(Unknown Source)
	at net.bitpot.railways.routesView.RoutesView.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:27)
	at net.bitpot.railways.routesView.RoutesView.getInstance(Unknown Source)
	at net.bitpot.railways.routesView.RoutesViewToolWindowFactory.createToolWindowContent(Unknown Source)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:542)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:521)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1033)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:979)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:681)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$default(ToolWindowManagerImpl.kt:659)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2052)
	at com.intellij.openapi.wm.impl.StripeButton.lambda$new$0(StripeButton.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.openapi.wm.impl.StripeButton.processMouseEvent(StripeButton.java:329)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.jgoodies.forms.layout.FormLayout PluginClassLoader(plugin=PluginDescriptor(name=Railways, id=Railways, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/RubyMine/ch-1/213.5744.124/RubyMine 2021.3 EAP.app.plugins/railways.jar, version=0.8.17, package=null, isBundled=false), packagePrefix=null, instanceId=107, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 75 more
```

My environment is:

```
RubyMine 2021.3 RC
Build #RM-213.5744.124, built on November 17, 2021
Licensed to - / Junichi Ito
Subscription is active until June 13, 2022.
Runtime version: 11.0.13+7-b1751.19 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 8
Non-Bundled Plugins:
    com.tabnine.TabNine (0.5.3)
    com.jetbrains.ChooseRuntime (1.2)
    com.intellij.plugins.watcher (213.5744.122)
    IdeaVIM (1.8.1)
    zielu.gittoolbox (212.8.1)
    org.jetbrains.plugins.vue (213.5744.122)
    intellij.prettierJS (213.5744.122)
    NodeJS (213.5744.122)
    Railways (0.8.17)
```

Gemfile.lock:

````
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.0.4.1)
      actionpack (= 6.0.4.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.4.1)
      actionpack (= 6.0.4.1)
      activejob (= 6.0.4.1)
      activerecord (= 6.0.4.1)
      activestorage (= 6.0.4.1)
      activesupport (= 6.0.4.1)
      mail (>= 2.7.1)
    actionmailer (6.0.4.1)
      actionpack (= 6.0.4.1)
      actionview (= 6.0.4.1)
      activejob (= 6.0.4.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.4.1)
      actionview (= 6.0.4.1)
      activesupport (= 6.0.4.1)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.4.1)
      actionpack (= 6.0.4.1)
      activerecord (= 6.0.4.1)
      activestorage (= 6.0.4.1)
      activesupport (= 6.0.4.1)
      nokogiri (>= 1.8.5)
    actionview (6.0.4.1)
      activesupport (= 6.0.4.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.4.1)
      activesupport (= 6.0.4.1)
      globalid (>= 0.3.6)
    activemodel (6.0.4.1)
      activesupport (= 6.0.4.1)
    activerecord (6.0.4.1)
      activemodel (= 6.0.4.1)
      activesupport (= 6.0.4.1)
    activestorage (6.0.4.1)
      actionpack (= 6.0.4.1)
      activejob (= 6.0.4.1)
      activerecord (= 6.0.4.1)
      marcel (~> 1.0.0)
    activesupport (6.0.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    bindex (0.8.1)
    bootsnap (1.9.1)
      msgpack (~> 1.0)
    builder (3.2.4)
    byebug (11.1.3)
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.9)
    crass (1.0.6)
    erubi (1.10.0)
    ffi (1.15.4)
    globalid (0.5.2)
      activesupport (>= 5.0)
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.3)
      activesupport (>= 5.0.0)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.12.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    mini_portile2 (2.6.1)
    minitest (5.14.4)
    msgpack (1.4.2)
    nio4r (2.5.8)
    nokogiri (1.12.5)
      mini_portile2 (~> 2.6.1)
      racc (~> 1.4)
    public_suffix (4.0.6)
    puma (4.3.10)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.3)
    rack-proxy (0.7.0)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.0.4.1)
      actioncable (= 6.0.4.1)
      actionmailbox (= 6.0.4.1)
      actionmailer (= 6.0.4.1)
      actionpack (= 6.0.4.1)
      actiontext (= 6.0.4.1)
      actionview (= 6.0.4.1)
      activejob (= 6.0.4.1)
      activemodel (= 6.0.4.1)
      activerecord (= 6.0.4.1)
      activestorage (= 6.0.4.1)
      activesupport (= 6.0.4.1)
      bundler (>= 1.3.0)
      railties (= 6.0.4.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (6.0.4.1)
      actionpack (= 6.0.4.1)
      activesupport (= 6.0.4.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rake (13.0.6)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (2.1.1)
    rexml (3.2.5)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (4.0.3)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    spring (2.1.1)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.0)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.2)
    thor (1.1.0)
    thread_safe (0.3.6)
    tilt (2.0.10)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    webpacker (4.3.0)
      activesupport (>= 4.2)
      rack-proxy (>= 0.6.1)
      railties (>= 4.2)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.1)

PLATFORMS
  ruby

DEPENDENCIES
  bootsnap (>= 1.4.2)
  byebug
  capybara (>= 2.15)
  jbuilder (~> 2.7)
  listen (~> 3.2)
  puma (~> 4.1)
  rails (~> 6.0.4, >= 6.0.4.1)
  sass-rails (>= 6)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  sqlite3 (~> 1.4)
  turbolinks (~> 5)
  tzinfo-data
  web-console (>= 3.3.0)
  webdrivers
  webpacker (~> 4.0)

RUBY VERSION
   ruby 2.7.4p191

BUNDLED WITH
   2.1.4
````

Could you investigate this? If you need more detailed information, please let me know.

**Comment by JunichiIto** [comment]
[RubyMine 2021.3 has been released](https://twitter.com/rubymine/status/1465756884086968327), but the error still occurs. Could you investigate and fix it, please?

**Comment by xzile** [comment]
Possibly an issue with Rubymine itself: https://youtrack.jetbrains.com/issue/IDEA-279562

**Comment by Vesymos** [comment]
Hey, I am having same issue on my RubyMine 2021.3

Build #RM-213.5744.254, built on November 30, 2021
Runtime version: 11.0.13+7-b1751.19 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Is there any workaround for this? Thanks!

**Comment by xzile** [comment]
I ended up reverting to the previous stable of Rubymine for now.

**Comment by BenoitDeo** [comment]
same issue here => Build #RM-213.5744.254, built on November 30, 2021

**Comment by jmitchell238** [comment]
I would like to also report I am having this issue as well. Build #RM-213.5744.254

**Comment by iLucker93** [comment]
+1, not worked in RubyMine RubyMine 2021.3
Build #RM-213.5744.254, built on November 30, 2021

**Comment by JunichiIto** [comment]
I submitted a feature request to JetBrains:

[Please fix and release Railways plugin as an official plugin or a default feature : RUBY-29340](https://youtrack.jetbrains.com/issue/RUBY-29340)

**Comment by hurricup** [comment]
It works in 2021.3.2

![image](https://user-images.githubusercontent.com/2811330/152841278-700015b3-ecbe-4568-adac-6c431c57048a.png)

**Comment by JunichiIto** [comment]
@hurricup Thank you for letting me know. It works in 2021.3.1 too. Something might have been wrong with 2021.3. 

I close this issue.
